name: Check-EditorConfig

on: push

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm install -g editorconfig-checker
      - run: editorconfig-checker
